"""empty message

Revision ID: 016e8ca75169
Revises: cc5625268259
Create Date: 2023-01-20 17:32:19.872389

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '016e8ca75169'
down_revision = 'cc5625268259'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('crew',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.alter_column('crew',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
