"""empty message

Revision ID: 0577d16f87d3
Revises: 4874f2da4311
Create Date: 2023-01-20 03:42:33.271563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0577d16f87d3'
down_revision = '4874f2da4311'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members_specie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specie_id', sa.Integer(), nullable=True),
    sa.Column('people_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['people_id'], ['people.id'], ),
    sa.ForeignKeyConstraint(['specie_id'], ['specie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('members_specie')
    # ### end Alembic commands ###
