"""empty message

Revision ID: 0ec3a6b116d7
Revises: dd58c56c74a0
Create Date: 2023-01-20 15:46:45.926856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec3a6b116d7'
down_revision = 'dd58c56c74a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('birth_year',
               existing_type=sa.DATE(),
               type_=sa.String(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.alter_column('birth_year',
               existing_type=sa.String(length=120),
               type_=sa.DATE(),
               existing_nullable=False)

    # ### end Alembic commands ###
