"""empty message

Revision ID: 6b5f2852729c
Revises: 9e16b1b39d66
Create Date: 2023-01-21 03:22:12.505931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b5f2852729c'
down_revision = '9e16b1b39d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('featuring_starship', schema=None) as batch_op:
        batch_op.drop_constraint('featuring_starship_starship_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('featuring_starship_film_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'starship', ['starship_id'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key(None, 'film', ['film_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('featuring_vehicle', schema=None) as batch_op:
        batch_op.drop_constraint('featuring_vehicle_vehicle_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('featuring_vehicle_film_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key(None, 'film', ['film_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('filmography', schema=None) as batch_op:
        batch_op.drop_constraint('filmography_people_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['people_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('members_specie', schema=None) as batch_op:
        batch_op.drop_constraint('members_specie_specie_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('members_specie_people_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'specie', ['specie_id'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key(None, 'people', ['people_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint('people_specie_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'specie', ['specie_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint('planet_created_by_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['created_by_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('reg_starship', schema=None) as batch_op:
        batch_op.drop_constraint('reg_starship_people_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reg_starship_starship_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'people', ['people_id'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key(None, 'starship', ['starship_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('reg_vehicle', schema=None) as batch_op:
        batch_op.drop_constraint('reg_vehicle_people_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('reg_vehicle_vehicle_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'vehicle', ['vehicle_id'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key(None, 'people', ['people_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.drop_constraint('resident_planet_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('resident_people_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planet', ['planet_id'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key(None, 'people', ['people_id'], ['id'], ondelete='cascade')

    with op.batch_alter_table('specie_filmography', schema=None) as batch_op:
        batch_op.drop_constraint('specie_filmography_specie_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('specie_filmography_film_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'film', ['film_id'], ['id'], ondelete='cascade')
        batch_op.create_foreign_key(None, 'specie', ['specie_id'], ['id'], ondelete='cascade')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specie_filmography', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('specie_filmography_film_id_fkey', 'film', ['film_id'], ['id'])
        batch_op.create_foreign_key('specie_filmography_specie_id_fkey', 'specie', ['specie_id'], ['id'])

    with op.batch_alter_table('resident', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('resident_people_id_fkey', 'people', ['people_id'], ['id'])
        batch_op.create_foreign_key('resident_planet_id_fkey', 'planet', ['planet_id'], ['id'])

    with op.batch_alter_table('reg_vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reg_vehicle_vehicle_id_fkey', 'vehicle', ['vehicle_id'], ['id'])
        batch_op.create_foreign_key('reg_vehicle_people_id_fkey', 'people', ['people_id'], ['id'])

    with op.batch_alter_table('reg_starship', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('reg_starship_starship_id_fkey', 'starship', ['starship_id'], ['id'])
        batch_op.create_foreign_key('reg_starship_people_id_fkey', 'people', ['people_id'], ['id'])

    with op.batch_alter_table('planet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('planet_created_by_id_fkey', 'user', ['created_by_id'], ['id'])

    with op.batch_alter_table('people', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('people_specie_id_fkey', 'specie', ['specie_id'], ['id'])

    with op.batch_alter_table('members_specie', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('members_specie_people_id_fkey', 'people', ['people_id'], ['id'])
        batch_op.create_foreign_key('members_specie_specie_id_fkey', 'specie', ['specie_id'], ['id'])

    with op.batch_alter_table('filmography', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('filmography_people_id_fkey', 'people', ['people_id'], ['id'])

    with op.batch_alter_table('featuring_vehicle', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('featuring_vehicle_film_id_fkey', 'film', ['film_id'], ['id'])
        batch_op.create_foreign_key('featuring_vehicle_vehicle_id_fkey', 'vehicle', ['vehicle_id'], ['id'])

    with op.batch_alter_table('featuring_starship', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('featuring_starship_film_id_fkey', 'film', ['film_id'], ['id'])
        batch_op.create_foreign_key('featuring_starship_starship_id_fkey', 'starship', ['starship_id'], ['id'])

    # ### end Alembic commands ###
