"""empty message

Revision ID: 8838ad350b87
Revises: 0ec3a6b116d7
Create Date: 2023-01-20 15:56:25.175358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8838ad350b87'
down_revision = '0ec3a6b116d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.alter_column('opening_crawl',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=300),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('film', schema=None) as batch_op:
        batch_op.alter_column('opening_crawl',
               existing_type=sa.String(length=300),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    # ### end Alembic commands ###
