"""empty message

Revision ID: 8884060c9397
Revises: c1116b06e4bc
Create Date: 2023-01-20 16:51:19.733251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8884060c9397'
down_revision = 'c1116b06e4bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specie', schema=None) as batch_op:
        batch_op.alter_column('average_height',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               nullable=False)
        batch_op.alter_column('average_lifespan',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=120),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('specie', schema=None) as batch_op:
        batch_op.alter_column('average_lifespan',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('average_height',
               existing_type=sa.String(length=120),
               type_=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
