"""empty message

Revision ID: b8b1f4612929
Revises: 8d505c65a484
Create Date: 2023-01-19 00:10:29.248208

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b1f4612929'
down_revision = '8d505c65a484'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('films',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('episode_id', sa.Integer(), nullable=True),
    sa.Column('opening_crawl', sa.String(length=120), nullable=False),
    sa.Column('director', sa.String(length=120), nullable=False),
    sa.Column('producer', sa.String(length=120), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=False),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('edited', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('films')
    # ### end Alembic commands ###
