"""empty message

Revision ID: df2765050b77
Revises: 0d03237adfb4
Create Date: 2023-01-19 00:24:48.583999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df2765050b77'
down_revision = '0d03237adfb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('specie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('classification', sa.String(length=120), nullable=False),
    sa.Column('designation', sa.String(length=120), nullable=False),
    sa.Column('average_height', sa.Integer(), nullable=True),
    sa.Column('average_lifespan', sa.Integer(), nullable=True),
    sa.Column('eye_colors', sa.String(length=120), nullable=False),
    sa.Column('hair_colors', sa.String(length=120), nullable=False),
    sa.Column('skin_colors', sa.String(length=120), nullable=False),
    sa.Column('language', sa.String(length=120), nullable=False),
    sa.Column('homeworld_by_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=120), nullable=False),
    sa.Column('created', sa.DateTime(), nullable=False),
    sa.Column('edited', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['homeworld_by_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specie')
    # ### end Alembic commands ###
